#define ICON_CLOUD_PNG                0
#define ICON_CLOUD_FOG_PNG            1
#define ICON_CLOUD_FOG_ALT_PNG        2
#define ICON_CLOUD_FOG_MOON_PNG       3
#define ICON_CLOUD_FOG_MOON_ALT_PNG   4
#define ICON_CLOUD_FOG_SUN_PNG        5
#define ICON_CLOUD_FOG_SUN_ALT_PNG    6
#define ICON_CLOUD_HAIL_PNG           7
#define ICON_CLOUD_HAIL_ALT_PNG       8
#define ICON_CLOUD_HAIL_MOON_PNG      9
#define ICON_CLOUD_HAIL_MOON_ALT_PNG  10
#define ICON_CLOUD_HAIL_SUN_PNG       11
#define ICON_CLOUD_HAIL_SUN_ALT_PNG   12
#define ICON_CLOUD_LIGHTNING_PNG      13
#define ICON_CLOUD_LIGHTNING_MOON_PNG 14
#define ICON_CLOUD_LIGHTNING_SUN_PNG  15
#define ICON_CLOUD_MOON_PNG           16
#define ICON_CLOUD_RAIN_PNG           17
#define ICON_CLOUD_RAIN_1_PNG         18
#define ICON_CLOUD_RAIN_2_PNG         19
#define ICON_CLOUD_RAIN_3_PNG         20
#define ICON_CLOUD_RAIN_ALT_PNG       21
#define ICON_CLOUD_RAIN_MOON_PNG      22
#define ICON_CLOUD_RAIN_MOON_1_PNG    23
#define ICON_CLOUD_RAIN_MOON_2_PNG    24
#define ICON_CLOUD_RAIN_MOON_3_PNG    25
#define ICON_CLOUD_RAIN_MOON_ALT_PNG  26
#define ICON_CLOUD_RAIN_SUN_PNG       27
#define ICON_CLOUD_RAIN_SUN_0_PNG     28
#define ICON_CLOUD_RAIN_SUN_1_PNG     29
#define ICON_CLOUD_RAIN_SUN_2_PNG     30
#define ICON_CLOUD_RAIN_SUN_3_PNG     31
#define ICON_CLOUD_RAIN_SUN_4_PNG     32
#define ICON_CLOUD_RAIN_SUN_5_PNG     33
#define ICON_CLOUD_RAIN_SUN_6_PNG     34
#define ICON_CLOUD_RAIN_SUN_7_PNG     35
#define ICON_CLOUD_RAIN_SUN_ALT_PNG   36
#define ICON_CLOUD_REFRESH_PNG        37
#define ICON_CLOUD_SNOW_PNG           38
#define ICON_CLOUD_SNOW_ALT_PNG       39
#define ICON_CLOUD_SNOW_MOON_PNG      40
#define ICON_CLOUD_SNOW_MOON_ALT_PNG  41
#define ICON_CLOUD_SNOW_SUN_PNG       42
#define ICON_CLOUD_SNOW_SUN_ALT_PNG   43
#define ICON_CLOUD_SUN_PNG            44
#define ICON_CLOUD_SUN_0_PNG          45
#define ICON_CLOUD_SUN_1_PNG          46
#define ICON_CLOUD_SUN_2_PNG          47
#define ICON_CLOUD_SUN_3_PNG          48
#define ICON_CLOUD_SUN_4_PNG          49
#define ICON_CLOUD_UPLOAD_PNG         50
#define ICON_CLOUD_WIND_PNG           51
#define ICON_CLOUD_WIND_MOON_PNG      52
#define ICON_CLOUD_WIND_SUN_PNG       53
#define ICON_COMPASS_PNG              54
#define ICON_COMPASS_EAST_PNG         55
#define ICON_COMPASS_NORTH_PNG        56
#define ICON_COMPASS_SOUTH_PNG        57
#define ICON_COMPASS_WEST_PNG         58
#define ICON_DEGREES_CELCIUS_PNG      59
#define ICON_DEGREES_FAHRENHEIT_PNG   60
#define ICON_MOON_PNG                 61
#define ICON_MOON_FIRST_QUARTER_PNG   62
#define ICON_MOON_FULL_PNG            63
#define ICON_MOON_LAST_QUARTER_PNG    64
#define ICON_MOON_NEW_PNG             65
#define ICON_MOON_WANING_CRESCENT_PNG 66
#define ICON_MOON_WANING_GIBBOUS_PNG  67
#define ICON_MOON_WAXING_CRESCENT_PNG 68
#define ICON_MOON_WAXING_GIBBOUS_PNG  69
#define ICON_SHADES_PNG               70
#define ICON_SNOWFLAKE_PNG            71
#define ICON_SUN_PNG                  72
#define ICON_SUN_1_PNG                73
#define ICON_SUN_2_PNG                74
#define ICON_SUN_3_PNG                75
#define ICON_SUN_4_PNG                76
#define ICON_SUN_5_PNG                77
#define ICON_SUN_6_PNG                78
#define ICON_SUN_7_PNG                79
#define ICON_SUN_8_PNG                80
#define ICON_SUN_LOW_PNG              81
#define ICON_SUN_LOWER_PNG            82
#define ICON_SUNRISE_PNG              83
#define ICON_SUNSET_PNG               84
#define ICON_THERMOMETER_PNG          85
#define ICON_THERMOMETER_100_PNG      86
#define ICON_THERMOMETER_25_PNG       87
#define ICON_THERMOMETER_50_PNG       88
#define ICON_THERMOMETER_75_PNG       89
#define ICON_THERMOMETER_ZERO_PNG     90
#define ICON_TORNADO_PNG              91
#define ICON_UMBRELLA_PNG             92
#define ICON_WIND_PNG                 93
