{
 "title": "WeatherServe",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Temperature, Dewpoint & Humidity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "°C" }
   ],
   "targets": [
    {
     "alias": "Air Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tempAir",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         3
        ],
        "type": "top"
       }
      ]
     ]
    },
    {
     "alias": "Apparent T",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apparentT",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         3
        ],
        "type": "top"
       }
      ]
     ]
    },
    {
     "alias": "Dewpoint",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dewPoint",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         3
        ],
        "type": "top"
       }
      ]
     ]
    },
    {
     "alias": "Humidity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "RHAir",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         3
        ],
        "type": "top"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Barometric Pressure",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "hPa" }
   ],
   "targets": [
    {
     "alias": "Barometric Pressure",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pressure",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         3
        ],
        "type": "top"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wind Speed & Direction",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "km/h" }
   ],
   "targets": [
    {
     "alias": "Windspeed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "windSpeed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         3
        ],
        "type": "top"
       }
      ]
     ]
    },
    {
     "alias": "Wind Gust",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "windGustRec",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         3
        ],
        "type": "top"
       }
      ]
     ]
    },
    {
     "alias": "Current wind dir",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "windDir",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         3
        ],
        "type": "top"
       }
      ]
     ]
    },
    {
     "alias": "Avg wind dir",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "avgWindDir",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         3
        ],
        "type": "top"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Solar Radiation & UV",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "W/m²" }
   ],
   "targets": [
    {
     "alias": "Solar Radiation",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "solarRad",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         3
        ],
        "type": "top"
       }
      ]
     ]
    },
    {
     "alias": "UV Index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uvIndex",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         3
        ],
        "type": "top"
       }
      ]
     ]
    },
    {
     "alias": "Sunhours",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sunHoursDec",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         3
        ],
        "type": "top"
       }
      ]
     ]
    },
    {
     "alias": "Clearsky Rad",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ClearSkyRad",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         3
        ],
        "type": "top"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Precipitation & Evapotranspiration",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none", "label": "mm" }
   ],
   "targets": [
    {
     "alias": "Total Rain 24h",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "totalRain24h",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         3
        ],
        "type": "top"
       }
      ]
     ]
    },
    {
     "alias": "Rain Intensity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rainIntensity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         3
        ],
        "type": "top"
       }
      ]
     ]
    },
    {
     "alias": "Evapotranspiration",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ETday",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         3
        ],
        "type": "top"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Particulate Matter",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "µg/m³" }
   ],
   "targets": [
    {
     "alias": "PM 10",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PM10",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         3
        ],
        "type": "top"
       }
      ]
     ]
    },
    {
     "alias": "PM 2,5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PM25",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         3
        ],
        "type": "top"
       }
      ]
     ]
    },
    {
     "alias": "24h avg PM10",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "avgPm10_24h",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         3
        ],
        "type": "top"
       }
      ]
     ]
    },
    {
     "alias": "24h avg PM2,5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "avgPm25_24h",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         3
        ],
        "type": "top"
       }
      ]
     ]
    }
   ]
  }
 ]
}